### ISSUE TITLE
Tests not running as expected; error when using `tox -e func-py37`

### ISSUE THREAD

**Issue by andrewtruong** [wandb/yea-wandb#7]
## What I did
1. Cloned the `client` repo and made a branch from `master` for my metaflow integration.
2. Created an [example integration flow](https://gist.github.com/andrewtruong/af1f5c7cde6fc679152952d2c36457fb)
3. Added `yea` asserts to the top of that file.  The id is `metaflow.0.1`
4. When I run `yea r metaflow.0.1`, the test does not fail as expected (there should be 4 runs, but assert expects 999)
5. When I run `tox -e func-py37`, I get a [long error](https://gist.github.com/andrewtruong/07bd826089164382d8f37981fb64f528)

**Comment by raubitsj** [comment]
Thanks for the report, this was fixed here:
https://github.com/wandb/yea-wandb/commit/2261adf6324d56dfb15ddd5788624b68adb7a339
